### ISSUE TITLE
New member login and access to exclusive content

### ISSUE THREAD

**Issue by SamOBrienOlinger** [SamOBrienOlinger/1st-AGILE-Project#1]
# User Story for New Member #

As a User, I can select an option to sign up to join Cockapoo Club so that I can become a member. 
Becoming a member will give me access to content and functionality that non-members will not have. 

## Acceptance Criteria ##

  - User can easily find a 'join' or 'sign up' button to click and begin joining process
  - User can complete a form that enables them to create a username and password
  - User can view the Furry Fun Foto Gallery
  - User can book a dog training session 

## Tasks ##

  - [x] Create the HTML and CSS for the join button and add it to the navigation bar in the header of each page.
  
  - [x] Customise membership form
  - [x] Ensure that only a registered member can access the Furry Fun Foto Gallery and book a dog training session 
        
  - [x] Test the completed functionality.

**Comment by SamOBrienOlinger** [comment]
Add acceptance criteria for user story

**Comment by SamOBrienOlinger** [comment]
Add checkboxes to tasks
