### ISSUE TITLE
Current member login and account options

### ISSUE THREAD

**Issue by SamOBrienOlinger** [SamOBrienOlinger/1st-AGILE-Project#2]
# User Story for Current Member #

As a current member I can **sign in** so that I can access to content and functionality that non-members will not have. 

## Acceptance Criteria ##

  - User can easily sign in using their unique username and password, if either is incorrect then an alert with an error message will show.
  - User can check a box to choose for site to remember their login details
  - User can logout out at any time
  - User can change email address for their account easily. 

## Tasks ##

  - [x] Create the HTML and CSS for the login button and add it to the header of each page.
  - [x] Customise the relevant files in the templates folder
  - [x] Test the completed functionality.

**Comment by SamOBrienOlinger** [comment]
Add checkboxes to tasks

**Comment by SamOBrienOlinger** [comment]
The 'current member' user story is currently the highest priority.

**Comment by SamOBrienOlinger** [comment]
Closing this user story was part of exploring the options regarding Product Backlog Refinement, and needed to be reopened.
