### ISSUE TITLE
Booking a dog training session

### ISSUE THREAD

**Issue by SamOBrienOlinger** [SamOBrienOlinger/1st-AGILE-Project#3]
# User Story for booking a dog training session #

As a member I can choose a time and date slot on a calendar so that I can book a dog training session.

## Acceptance Criteria ##

  - Once signed in, the user can easily identify and click on a booking button that brings them to a calendar. 
  - User is able to choose a time and date.
  - User receives confirmation of their chosen time and date.
 
## Tasks ##

  - [ ] Create the HTML and CSS for the booking button. 
  
  - [ ] Add booking button to the header of each page after user signs in.
  
  - [ ] Create the code for the booking of a time and date.
 
  - [ ] Test the completed functionality.

**Comment by SamOBrienOlinger** [comment]
Add another user story regarding a key feature for members, being able to book a dog training session.
