### ISSUE TITLE
Purchasing merchandise

### ISSUE THREAD

**Issue by SamOBrienOlinger** [SamOBrienOlinger/1st-AGILE-Project#4]
# User Story for purchasing merchandise #

As a user I can access an online shop section so that I can purchase merchandise.

## Acceptance Criteria ##

  - User can easily identify and click on a shop button that brings them to a menu of merchandise. 
  - User is able to add items to a cart.
  - User can pay for their item.
  - User can choose to collect the items they have purchased or have these delivered.  
 
## Tasks ##

  - [ ] Create the HTML and CSS for the shop button.
  - [ ] Create the merchandise page/section using HTML and CSS.
  - [ ] Create feature for adding items to cart.
  - [ ] Create feature for user to pay for items.
  - [ ] Add a way for user to choose between collection and delivery options. 
  - [ ] Test the completed functionality.

**Comment by SamOBrienOlinger** [comment]
This feature is available to members and non-members, to maximise the number of users who can purchase merchandise.
